class MetaPath:
    def __init__(self, pattern: str): ...


class GraphBuilder:
    def __init__(self): ...
    def add_node(self,
                 type: str,
                 *,
                 properties: dict[str, str] | None = None) -> NodeRef: ...
    def add_edge(self,
                 source: NodeRef,
                 destination: NodeRef,
                 type: str,
                 *,
                 properties: dict[str, str] | None = None): ...
    def build(self) -> Graph: ...


class NodeRef:
    ...


class Graph:
    def node_list(self) -> list[(int, str)]: ...
    def edge_list(self) -> list[(int, int, str, int)]: ...
    def meta_path_subgraph(self, metapaths: dict[str, MetaPath]) -> Graph: ...
    def node_properties(self, node: int) -> dict[str, str]: ...
    def edge_properties(self, source: int, destination: int, type: str) -> dict[str, str]: ...

