import typing


class MetaPath:
    def __init__(self, pattern: str): ...
    def reverse(self) -> typing.Self: ...


class GraphBuilder:
    def __init__(self): ...
    def add_node(self,
                 type: str,
                 *,
                 properties: dict[str, str] | None = None) -> NodeRef: ...
    def add_edge(self,
                 source: NodeRef,
                 destination: NodeRef,
                 type: str,
                 *,
                 weight: float = 1.0,
                 properties: dict[str, str] | None = None): ...
    def build(self) -> Graph: ...


class NodeDescriptor:
    @property
    def type(self) -> str: ...
    @property
    def uid(self) -> NodeRef: ...


class EdgeDescriptor:
    @property
    def source(self) -> NodeRef: ...
    @property
    def destination(self) -> NodeRef: ...
    @property
    def type(self) -> str: ...
    @property
    def uid(self) -> EdgeRef: ...
    @property
    def weight(self) -> float: ...


class NodeRef:
    ...

class EdgeRef:
    ...


class Graph:
    def node_info(self, node: NodeRef, /) -> NodeDescriptor: ...
    def node_list(self) -> list[NodeDescriptor]: ...
    def edge_list(self) -> list[EdgeDescriptor]: ...
    def meta_path_subgraph(self,
                           metapaths: dict[str, MetaPath],
                           *,
                           unique_nodes=True) -> Graph: ...
    def node_properties(self, node: NodeRef, /) -> dict[str, str]: ...
    def edge_properties(self, edge: EdgeRef, /) -> dict[str, str]: ...
    def update_weights(self, weigths: dict[EdgeRef, float]) -> typing.Self: ...
    def to_markov_graph(self) -> typing.Self: ...
    def deduplicate_edges(
        self,
        types: list[str], *,
        data_handling: typing.Literal['discard', 'enforce_identical'],
        weight_handling: typing.Literal['set_to_one', 'enforce_identical', 'sum_aggregate']) -> Graph: ...
    def random_walk(self,
                    start: NodeRef, *,
                    weighted: bool = True,
                    path_length: int = 10,
                    p: float = 1.0,
                    q: float = 1.0) -> list[NodeRef]:
        ...
    def random_walk_distribution(self,
                                 start: NodeRef, *,
                                 weighted: bool = True,
                                 path_length: int = 10,
                                 p: float = 1.0,
                                 q: float = 1.0,
                                 n_iter: int = 100) -> dict[NodeRef, int]:
        ...
